/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mannagement;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ragha
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    private String Email;
   
    public AdminMenu() {
        
        initComponents();
        if(!AdminLogin.Email.equals(AdminLogin.rootEmail)){
            SectionBtn.setVisible(false);
            ClassBtn.setVisible(false);
            SubjectBtn.setVisible(false);
            AdminBtn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SubjectBtn = new javax.swing.JButton();
        StudentBtn = new javax.swing.JButton();
        TeacherBtn = new javax.swing.JButton();
        SectionBtn = new javax.swing.JButton();
        ClassBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        SubjectBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SubjectBtn.setText("Subjects");
        SubjectBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectBtnActionPerformed(evt);
            }
        });

        StudentBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        StudentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentBtn.setLabel("Student");
        StudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBtnActionPerformed(evt);
            }
        });

        TeacherBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TeacherBtn.setText("Teacher");
        TeacherBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherBtnActionPerformed(evt);
            }
        });

        SectionBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SectionBtn.setText("Sections");
        SectionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionBtnActionPerformed(evt);
            }
        });

        ClassBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ClassBtn.setText("Classes");
        ClassBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassBtnActionPerformed(evt);
            }
        });

        AdminBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AdminBtn.setText("Admins");
        AdminBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutBtn.setText("LogOut");
        LogoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TeacherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectBtnActionPerformed
        try {
            // TODO add your handling code here:
            new SubjectGUI().setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SubjectBtnActionPerformed

    private void StudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBtnActionPerformed
        // TODO add your handling code here:
        new StudentGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_StudentBtnActionPerformed

    private void TeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherBtnActionPerformed
        // TODO add your handling code here:
        new TeachersGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_TeacherBtnActionPerformed

    private void SectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionBtnActionPerformed
        // TODO add your handling code here:
        new SectionsGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_SectionBtnActionPerformed

    private void ClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassBtnActionPerformed
        // TODO add your handling code here:
        new ClassesGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_ClassBtnActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
        new AdminsGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        new AdminLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton ClassBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton SectionBtn;
    private javax.swing.JButton StudentBtn;
    private javax.swing.JButton SubjectBtn;
    private javax.swing.JButton TeacherBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
