/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mannagement;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static school_mannagement.Validations.emailValid;

/**
 *
 * @author ragha
 */
public class ShowAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ShowAdmin
     */
     private String Fname="";
    private String Lname="";
    private String Gender="";
    private String Birth_date="";
    private String Mob_no="";
    private String Email="";
    private String ImagePath="";
    private String ImageName="";
    private BufferedImage bi ;
    private String Password="";
    String newBirthDate="";
    String newGender="";
    String[] date;
    //required classes obects
        Validations valid=new Validations();
        GetComponentData fillData=new GetComponentData();
        TeacherFormGUI tf=new TeacherFormGUI();
    public ShowAdmin(String Email)throws Exception {
        this.Email=Email;
        initComponents();
         setValues();
    }
void setValues()throws Exception{
        
        
        Map<String,String> TeachData=Admin.getAdminData(Email);
        
        for(String key:TeachData.keySet()){
                 System.out.println(key+" "+TeachData.get(key));
             }
        
        
        FnameField.setText(TeachData.get("fname"));
          LnameField.setText(TeachData.get("lname"));
        //For setting gender
        Gender=TeachData.get("gender");
        System.out.println(Gender);
        if(Gender.equals(MaleRadio.getText()))
            MaleRadio.setSelected(true);
        else
            FemaleRadio.setSelected(true);
        //Setting birthdate
        Birth_date=TeachData.get("birth_date");
        date=Birth_date.split("-");
        monthBox.setSelectedIndex(Integer.parseInt(date[1]));
        dayBox.setSelectedIndex(Integer.parseInt(date[2])-1);
        yearBox.setSelectedItem(date[0]);
        Mob_no=TeachData.get("mob");
        MobField.setText(Mob_no);
        emailField.setText(TeachData.get("email"));
        //Setting password
       passwordField.setEchoChar((char)0);
        passwordField.setText(TeachData.get("password"));
        //setting image
            ImagePath=TeachData.get("image").replace((char)44,'\\');
            System.out.println(ImagePath+" \n is path of image");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(ImagePath).getImage().getScaledInstance(imageLabel.getHeight(), imageLabel.getWidth(),Image.SCALE_DEFAULT ));        
            imageLabel.setIcon(imageIcon);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        FemaleRadio = new javax.swing.JRadioButton();
        MaleRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        monthBox = new javax.swing.JComboBox<>();
        MobField = new javax.swing.JTextField();
        dayBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox<>();
        passwordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConfirmPassField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FnameField = new javax.swing.JTextField();
        LnameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        EditLname = new javax.swing.JButton();
        EditGender = new javax.swing.JButton();
        EditBirth = new javax.swing.JButton();
        EditMob = new javax.swing.JButton();
        EditMail = new javax.swing.JButton();
        EditFname = new javax.swing.JButton();
        EditPass = new javax.swing.JButton();
        EditImageBtn = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        RemoveAdminBtn = new javax.swing.JButton();
        BackToTeachers1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Last Name");

        buttonGroup1.add(FemaleRadio);
        FemaleRadio.setText("Female");
        FemaleRadio.setEnabled(false);
        FemaleRadio.setName("Female"); // NOI18N
        FemaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(MaleRadio);
        MaleRadio.setText("Male");
        MaleRadio.setEnabled(false);
        MaleRadio.setName("Male"); // NOI18N
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Aprail", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthBox.setSelectedIndex(9);
        monthBox.setEnabled(false);
        monthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthBoxActionPerformed(evt);
            }
        });

        MobField.setEditable(false);
        MobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobFieldActionPerformed(evt);
            }
        });
        MobField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MobFieldKeyReleased(evt);
            }
        });

        dayBox.setToolTipText("Select Day");
        dayBox.setEnabled(false);
        fillData.dayItemInsertion(dayBox, monthBox);
        dayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Mob No.");

        yearBox.setEnabled(false);
        fillData.yearItemInsertion(dayBox, monthBox, yearBox);

        passwordField.setEditable(false);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Birth Date");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Confirm Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        ConfirmPassField.setEditable(false);
        ConfirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("E-mail");

        emailField.setEnabled(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        FnameField.setEditable(false);
        FnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameFieldActionPerformed(evt);
            }
        });
        FnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameFieldKeyReleased(evt);
            }
        });

        LnameField.setEditable(false);
        LnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameFieldActionPerformed(evt);
            }
        });
        LnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameFieldKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Register");

        EditLname.setText("Edit");
        EditLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLnameActionPerformed(evt);
            }
        });

        EditGender.setText("Edit");
        EditGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditGenderActionPerformed(evt);
            }
        });

        EditBirth.setText("Edit");
        EditBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBirthActionPerformed(evt);
            }
        });

        EditMob.setText("Edit");
        EditMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMobActionPerformed(evt);
            }
        });

        EditMail.setText("Edit");
        EditMail.setEnabled(false);
        EditMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMailActionPerformed(evt);
            }
        });

        EditFname.setText("Edit");
        EditFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFnameActionPerformed(evt);
            }
        });

        EditPass.setText("Edit");
        EditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPassActionPerformed(evt);
            }
        });

        EditImageBtn.setText("Update Image");
        EditImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditImageBtnActionPerformed(evt);
            }
        });

        RemoveAdminBtn.setText("Remove Admin");
        RemoveAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAdminBtnActionPerformed(evt);
            }
        });

        BackToTeachers1.setText("Back To Admin");
        BackToTeachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToTeachers1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(MaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(FemaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(EditLname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(EditFname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(EditBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EditImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(197, 197, 197))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(EditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditMail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MobField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditMob, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(BackToTeachers1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(RemoveAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(MaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FemaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(EditImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EditMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MobField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditMob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToTeachers1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FemaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void monthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthBoxActionPerformed
        // TODO add your handling code here:
        fillData.dayItemInsertion(dayBox, monthBox);
    }//GEN-LAST:event_monthBoxActionPerformed

    private void MobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobFieldActionPerformed

    private void MobFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobFieldKeyReleased
        // TODO add your handling code here:
        Mob_no=fillData.checkValidUpdate(MobField,EditMob,valid.mobValid(MobField.getText()));
    }//GEN-LAST:event_MobFieldKeyReleased

    private void dayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayBoxActionPerformed
        // TODO add your handling code here:
        fillData.yearItemInsertion(dayBox, monthBox, yearBox);
    }//GEN-LAST:event_dayBoxActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void ConfirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPassFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:

        Email=fillData.checkValidUpdate(emailField,EditMail,valid.emailValid(emailField.getText()));
    }//GEN-LAST:event_emailFieldKeyReleased

    private void FnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameFieldActionPerformed

    private void FnameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameFieldKeyReleased

        Fname=fillData.checkValidUpdate(FnameField,EditFname,valid.Name(FnameField.getText()));
    }//GEN-LAST:event_FnameFieldKeyReleased

    private void LnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameFieldActionPerformed

    private void LnameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameFieldKeyReleased
        // TODO add your handling code here:

        Lname=fillData.checkValidUpdate(LnameField,EditLname,valid.Name(LnameField.getText()));
    }//GEN-LAST:event_LnameFieldKeyReleased

    private void EditLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLnameActionPerformed
        // TODO add your handling code here:
        LnameField.setEditable(true);

        if(Lname!=""){

            try {
               Admin.updateAdminData("admin",Email,"lname",Lname);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            Lname="";
            LnameField.setEditable(false);

        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));
            EditLname.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditLnameActionPerformed

    private void EditGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditGenderActionPerformed
        // TODO add your handling code here:
        try{
            MaleRadio.setEnabled(true);
            FemaleRadio.setEnabled(true);
            if(MaleRadio.isSelected())
            newGender=MaleRadio.getText();
            else
            newGender=FemaleRadio.getText();
            if(!Gender.equals(newGender)){
                if(MaleRadio.isSelected()){
                    Admin.updateAdminData("admin", Email, "gender", MaleRadio.getText());
                    Gender=MaleRadio.getText();
                    newGender="";
                    MaleRadio.setEnabled(false);
                    FemaleRadio.setEnabled(false);
                }else{
                    Admin.updateAdminData("admin", Email, "gender", FemaleRadio.getText());
                    Gender=FemaleRadio.getText();
                    newGender="";
                    MaleRadio.setEnabled(false);
                    FemaleRadio.setEnabled(false);
                }
            }
        }catch(Exception e){ }
    }//GEN-LAST:event_EditGenderActionPerformed

    private void EditBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBirthActionPerformed
        // TODO add your handling code here:
        monthBox.setEnabled(true);
        dayBox.setEnabled(true);
        yearBox.setEnabled(true);
        String month;

        if(monthBox.getSelectedIndex()>9)
        month=""+monthBox.getSelectedIndex();
        else
        month="0"+monthBox.getSelectedIndex();

        newBirthDate=yearBox.getSelectedItem().toString()+"-"+month+"-"+dayBox.getSelectedItem().toString();
        System.out.println(newBirthDate+" is new birthDate");
        System.out.println(Birth_date+" is birthDate");
        if(!Birth_date.equals(newBirthDate)){

            try {
                Admin.updateAdminData("admin", Email, "birth_date", newBirthDate);
                monthBox.setEnabled(false);
                dayBox.setEnabled(false);
                yearBox.setEnabled(false);
                Birth_date=yearBox.getSelectedItem().toString()+"-"+month+"-"+dayBox.getSelectedItem().toString();
                newBirthDate="";
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_EditBirthActionPerformed

    private void EditMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMobActionPerformed
        // TODO add your handling code here:
        MobField.setEditable(true);

        if(Mob_no!=""){

            try {
                Admin.updateAdminData("person",Email,"mob_no",Mob_no);
                Mob_no="";
                MobField.setEditable(false);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));
            EditMob.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditMobActionPerformed

    private void EditMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMailActionPerformed
        // TODO add your handling code here:
        emailField.setEditable(true);

        if(Email!=""){

            try {
                Admin.updateAdminData("admin",Email,"email",Email);
                Email="";
                emailField.setEditable(false);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));
            EditMail.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditMailActionPerformed

    private void EditFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFnameActionPerformed
        // TODO add your handling code here:
        FnameField.setEditable(true);

        if(Fname!=""){

            try {
                Admin.updateAdminData("admin",Email,"fname",Fname);
                Fname="";
                FnameField.setEditable(false);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));
            EditFname.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditFnameActionPerformed

    private void EditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPassActionPerformed
        // TODO add your handling code here:
        passwordField.setEditable(true);
        ConfirmPassField.setEditable(true);
        if(passwordField.getText().equals(ConfirmPassField.getText()) && !passwordField.getText().isBlank()){
            try {
                Password=passwordField.getText();
                System.out.println(Password+" password is equal");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditPass.getHeight(),EditPass.getWidth(),Image.SCALE_DEFAULT ));
                EditPass.setIcon(imageIcon);
                Admin.updateAdminData("admin",Email,"password",Password);
                passwordField.setEditable(false);
                ConfirmPassField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditPass.getHeight(),EditPass.getWidth(),Image.SCALE_DEFAULT ));        
        EditPass.setIcon(imageIcon);
        return;

        }
    }//GEN-LAST:event_EditPassActionPerformed

    private void EditImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditImageBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser imageFileChooser=new JFileChooser();
        //FileNameExtensionFilter imgFilter=new FileNameExtensionFilter("Jpg Only(.jpg)","jpg","png");
        int selected=imageFileChooser.showOpenDialog(null);
        if(selected==imageFileChooser.APPROVE_OPTION){

            try {
                File Img=imageFileChooser.getSelectedFile();
                ImageName=imageFileChooser.getSelectedFile().getName();
                bi= ImageIO.read(Img);
                Image newImage = bi.getScaledInstance(imageLabel.getHeight(), imageLabel.getWidth(), Image.SCALE_DEFAULT);
                imageLabel.setIcon(new ImageIcon(newImage));
                ImageName=ImageName.replace(".", Mob_no+".");
                File oldImage=new File(ImagePath);
                if(oldImage.delete() || !oldImage.exists()){
                    System.out.println(ImagePath+"\nOld image is deleted");
                    ImagePath="C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\StuTeachImages\\"+ImageName+"";
                    System.out.println(ImagePath);
                    ImageIO.write(bi, "jpg", new File(ImagePath));
                    ImageIO.write(bi, "png", new File(ImagePath));
                    ImageIO.write(bi, "gif", new File(ImagePath));
                    ImageIO.write(bi, "bmp", new File(ImagePath));
                    ImagePath=ImagePath.replace((char)92,(char)44);

                    try {
                        Admin.updateAdminData("admin", Email, "image", ImagePath);
                    } catch (Exception ex) {
                        java.util.logging.Logger.getLogger(ShowStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }

                    ImagePath="C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\StuTeachImages\\"+ImageName+"";
                }
                else{
                    System.out.println(ImagePath);
                    System.out.println("Image not deleted");
                }//end of delimage if
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(TeacherFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_EditImageBtnActionPerformed

    private void RemoveAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAdminBtnActionPerformed
         try {
             Admin.removeAdmin(Email);
             dispose();
         } catch (Exception ex) {
             Logger.getLogger(ShowAdmin.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_RemoveAdminBtnActionPerformed

    private void BackToTeachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToTeachers1ActionPerformed
        // TODO add your handling code here:
        new AdminsGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToTeachers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowAdmin("raghav@gn.com").setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ShowAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToTeachers1;
    private javax.swing.JPasswordField ConfirmPassField;
    private javax.swing.JButton EditBirth;
    private javax.swing.JButton EditFname;
    private javax.swing.JButton EditGender;
    private javax.swing.JButton EditImageBtn;
    private javax.swing.JButton EditLname;
    private javax.swing.JButton EditMail;
    private javax.swing.JButton EditMob;
    private javax.swing.JButton EditPass;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JTextField FnameField;
    private javax.swing.JTextField LnameField;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField MobField;
    private javax.swing.JButton RemoveAdminBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dayBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
