/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mannagement;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author ragha
 */
public class ShowTeacher extends javax.swing.JFrame {

    /**
     * Creates new form ShowTeacher
     */
     
    private String Fname="";
    private String Lname="";
    private String Gender="";
    private String Birth_date="";
    private String Mob_no="";
    private String Email="";
    private String ImagePath="";
    private String ImageName="";
    private BufferedImage bi ;
    private String P_id;
    private String Qualification="";
    private String class_id="";
    private LocalDate Join_date;
    private LocalDate Leave_date;
    private Object SelectedSub[];
    String newClass_id="";
    String[] date;
    String newBirthDate="";
    String newGender="";
    //required classes obects
        Validations valid=new Validations();
        GetComponentData fillData=new GetComponentData();
        TeacherFormGUI tf=new TeacherFormGUI();
        Subject sub=new Subject();
        
    /** Creates new form TeacherFormGUI */
    public ShowTeacher(String P_id)throws Exception {
        this.P_id=P_id;
       
        initComponents();
         try{
setValues();
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FnameField = new javax.swing.JTextField();
        LnameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JoinLabel = new javax.swing.JLabel();
        ClassBox = new javax.swing.JComboBox<>();
        QualField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        MobField = new javax.swing.JTextField();
        monthBox = new javax.swing.JComboBox<>();
        dayBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JComboBox<>();
        FemaleRadio = new javax.swing.JRadioButton();
        MaleRadio = new javax.swing.JRadioButton();
        EditImageBtn = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubjectList = new javax.swing.JList<>();
        LeaveSchoolBtn = new javax.swing.JButton();
        EditMail = new javax.swing.JButton();
        EditClass = new javax.swing.JButton();
        EditFname = new javax.swing.JButton();
        EditLname = new javax.swing.JButton();
        EditQual = new javax.swing.JButton();
        EditSubject = new javax.swing.JButton();
        EditBirth = new javax.swing.JButton();
        EditGender = new javax.swing.JButton();
        EditMob = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LeaveLabel = new javax.swing.JLabel();
        BackToTeachers1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Show Teacher");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        FnameField.setEditable(false);
        FnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameFieldActionPerformed(evt);
            }
        });
        FnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameFieldKeyReleased(evt);
            }
        });

        LnameField.setEditable(false);
        LnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameFieldActionPerformed(evt);
            }
        });
        LnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameFieldKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Birth Date");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Mob No.");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("E-mail");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setText("Qualification");

        JoinLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        try{
            fillData.ClassItemInsertion(ClassBox);
        }catch(Exception e){ }
        ClassBox.setEditable(true);
        ClassBox.setEnabled(false);

        QualField.setEditable(false);
        QualField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualFieldActionPerformed(evt);
            }
        });
        QualField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QualFieldKeyReleased(evt);
            }
        });

        emailField.setEditable(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
        });

        MobField.setEditable(false);
        MobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobFieldActionPerformed(evt);
            }
        });
        MobField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MobFieldKeyReleased(evt);
            }
        });

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Aprail", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthBox.setSelectedIndex(9);
        monthBox.setEnabled(false);
        monthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthBoxActionPerformed(evt);
            }
        });

        dayBox.setToolTipText("Select Day");
        dayBox.setEnabled(false);
        fillData.dayItemInsertion(dayBox, monthBox);
        dayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayBoxActionPerformed(evt);
            }
        });

        yearBox.setEnabled(false);
        fillData.yearItemInsertion(dayBox, monthBox, yearBox);

        buttonGroup1.add(FemaleRadio);
        FemaleRadio.setText("Female");
        FemaleRadio.setEnabled(false);
        FemaleRadio.setName("Female"); // NOI18N
        FemaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(MaleRadio);
        MaleRadio.setText("Male");
        MaleRadio.setEnabled(false);
        MaleRadio.setName("Male"); // NOI18N
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        EditImageBtn.setText("Update Image");
        EditImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditImageBtnActionPerformed(evt);
            }
        });

        try{
            SubjectList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = Teacher.showTeachSubjects(P_id);
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            SubjectList.setEnabled(false);
        }catch(Exception e){}
        jScrollPane1.setViewportView(SubjectList);

        LeaveSchoolBtn.setText("Leave School");
        LeaveSchoolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveSchoolBtnActionPerformed(evt);
            }
        });

        EditMail.setText("Edit");
        EditMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMailActionPerformed(evt);
            }
        });

        EditClass.setText("Edit");
        EditClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClassActionPerformed(evt);
            }
        });

        EditFname.setText("Edit");
        EditFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFnameActionPerformed(evt);
            }
        });

        EditLname.setText("Edit");
        EditLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditLnameActionPerformed(evt);
            }
        });

        EditQual.setText("Edit");
        EditQual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditQualActionPerformed(evt);
            }
        });

        EditSubject.setText("Update Subjects");
        EditSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubjectActionPerformed(evt);
            }
        });

        EditBirth.setText("Edit");
        EditBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBirthActionPerformed(evt);
            }
        });

        EditGender.setText("Edit");
        EditGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditGenderActionPerformed(evt);
            }
        });

        EditMob.setText("Edit");
        EditMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMobActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setText("Class Teach");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Leave Date");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Join Date");

        LeaveLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        BackToTeachers1.setText("Back To Teachers");
        BackToTeachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToTeachers1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(MaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(FemaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MobField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditMob, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(JoinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LeaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QualField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditClass)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditFname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditLname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditQual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditMail, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                                .addComponent(EditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(BackToTeachers1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(LeaveSchoolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1016, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(EditImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(EditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FemaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(MobField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EditMob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QualField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditQual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditClass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JoinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LeaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToTeachers1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeaveSchoolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(448, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(111, 111, 111)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameFieldActionPerformed

    private void FnameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameFieldKeyReleased

        Fname=fillData.checkValidUpdate(FnameField,EditFname,valid.Name(FnameField.getText()));
    }//GEN-LAST:event_FnameFieldKeyReleased

    private void LnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameFieldActionPerformed

    private void LnameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameFieldKeyReleased
        // TODO add your handling code here:

        Lname=fillData.checkValidUpdate(LnameField,EditLname,valid.Name(LnameField.getText()));
    }//GEN-LAST:event_LnameFieldKeyReleased

    private void QualFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QualFieldActionPerformed

    private void QualFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QualFieldKeyReleased
        // TODO add your handling code here:
        Qualification=fillData.checkValidUpdate(QualField,EditQual,valid.qualValid(QualField.getText()));
    }//GEN-LAST:event_QualFieldKeyReleased

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:

        Email=fillData.checkValidUpdate(emailField,EditMail,valid.emailValid(emailField.getText()));
    }//GEN-LAST:event_emailFieldKeyReleased

    private void MobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobFieldActionPerformed

    private void MobFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobFieldKeyReleased
        // TODO add your handling code here:

        Mob_no=fillData.checkValidUpdate(MobField,EditMob,valid.mobValid(MobField.getText()));
    }//GEN-LAST:event_MobFieldKeyReleased

    private void monthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthBoxActionPerformed
        // TODO add your handling code here:
        fillData.dayItemInsertion(dayBox, monthBox);
    }//GEN-LAST:event_monthBoxActionPerformed

    private void dayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayBoxActionPerformed
        // TODO add your handling code here:
        fillData.yearItemInsertion(dayBox, monthBox, yearBox);
    }//GEN-LAST:event_dayBoxActionPerformed

    private void FemaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void EditImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditImageBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser imageFileChooser=new JFileChooser();
        //FileNameExtensionFilter imgFilter=new FileNameExtensionFilter("Jpg Only(.jpg)","jpg","png");
        int selected=imageFileChooser.showOpenDialog(null);
        if(selected==imageFileChooser.APPROVE_OPTION){

            try {
                File Img=imageFileChooser.getSelectedFile();
                ImageName=imageFileChooser.getSelectedFile().getName();
                bi= ImageIO.read(Img);
                Image newImage = bi.getScaledInstance(imageLabel.getHeight(), imageLabel.getWidth(), Image.SCALE_DEFAULT);
                imageLabel.setIcon(new ImageIcon(newImage));
                ImageName=ImageName.replace(".", P_id+".");
                File oldImage=new File(ImagePath);  
                if(oldImage.delete() || !oldImage.exists()){
                    System.out.println(ImagePath+"\nOld image is deleted");
                ImagePath="C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\StuTeachImages\\"+ImageName+"";
          System.out.println(ImagePath);
          ImageIO.write(bi, "jpg", new File(ImagePath));
          ImageIO.write(bi, "png", new File(ImagePath));
          ImageIO.write(bi, "gif", new File(ImagePath));
          ImageIO.write(bi, "bmp", new File(ImagePath));
                ImagePath=ImagePath.replace((char)92,(char)44);
                try {
                    Teacher.updateTeacherData("person", P_id, "image", ImagePath);
                } catch (Exception ex) {
                    Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImagePath="C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\StuTeachImages\\"+ImageName+"";
            }
                else{
                    System.out.println(ImagePath);
                    System.out.println("Image not deleted");
                }//end of delimage if
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(TeacherFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_EditImageBtnActionPerformed

    private void LeaveSchoolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveSchoolBtnActionPerformed
        try {
            // TODO add your handling code here:
            Leave_date=LocalDate.now();
            Teacher.removeTeacher(Leave_date, P_id);
            LeaveSchoolBtn.setEnabled(false);
            LeaveLabel.setText(Leave_date.toString());
        } catch (Exception ex) {
            Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LeaveSchoolBtnActionPerformed

    private void EditMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMailActionPerformed
        // TODO add your handling code here:
        emailField.setEditable(true);
        
        if(Email!=""){
            try {
                Teacher.updateTeacherData("person",P_id,"email",Email);
                Email="";
                emailField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));        
            EditMail.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditMailActionPerformed

    private void EditClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClassActionPerformed
        // TODO add your handling code here:
        ClassBox.setEnabled(true);
            try {
                newClass_id=ClassBox.getSelectedItem().toString();
                if(class_id!=newClass_id){
                Teacher.updateTeacherData("teacher",P_id,"class_id",class_id);
                ClassBox.setEnabled(false);
                class_id=ClassBox.getSelectedItem().toString();
                newClass_id="";
                }
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\valid.png").getImage().getScaledInstance(EditClass.getHeight(), EditClass.getWidth(),Image.SCALE_DEFAULT ));        
            EditClass.setIcon(imageIcon);
            
    }//GEN-LAST:event_EditClassActionPerformed

    private void EditFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFnameActionPerformed
        // TODO add your handling code here:
        FnameField.setEditable(true);
        
        if(Fname!=""){
            try {
                Teacher.updateTeacherData("person",P_id,"fname",Fname);
                Fname="";
                FnameField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));        
            EditFname.setIcon(imageIcon);
        }
        
    }//GEN-LAST:event_EditFnameActionPerformed

    private void EditLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditLnameActionPerformed
        // TODO add your handling code here:
        LnameField.setEditable(true);
        
        if(Lname!=""){
            try {
                Teacher.updateTeacherData("person",P_id,"lname",Lname);
                Lname="";
                LnameField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));        
            EditLname.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditLnameActionPerformed

    private void EditQualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditQualActionPerformed
        // TODO add your handling code here:
        QualField.setEditable(true);
        
        if(Qualification!=""){
            try {
                Teacher.updateTeacherData("teacher",P_id,"qualification",Qualification);
                Qualification="";
                QualField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));        
            EditQual.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditQualActionPerformed

    private void EditSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubjectActionPerformed
        try {
            // TODO add your handling code here:
            SubjectList.setEnabled(true);
            if(SubjectList.getSelectedIndices().length<1){
            SubjectList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = tf.getTableData();
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
            });
            }
            List<String> sublist=SubjectList.getSelectedValuesList();
            if(sublist.size()>0){
                try {
                    Teacher.updateTeachSub(sublist, P_id);
                    SubjectList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = Teacher.showTeachSubjects(P_id);
                @Override
                public int getSize() { return strings.length; }
                @Override
                public String getElementAt(int i) { return strings[i]; }
            });
                    SubjectList.setEnabled(false);
                } catch (Exception ex) {
                    Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditSubjectActionPerformed

    private void EditBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBirthActionPerformed
        // TODO add your handling code here:
        monthBox.setEnabled(true);
        dayBox.setEnabled(true);
        yearBox.setEnabled(true);
        String month;
        
        if(monthBox.getSelectedIndex()>9)
            month=""+monthBox.getSelectedIndex();
            else
            month="0"+monthBox.getSelectedIndex();
        
        newBirthDate=yearBox.getSelectedItem().toString()+"-"+month+"-"+dayBox.getSelectedItem().toString();
        System.out.println(newBirthDate+" is new birthDate");
        System.out.println(Birth_date+" is birthDate");
        if(!Birth_date.equals(newBirthDate)){
            try {
                
                Teacher.updateTeacherData("person", P_id, "birth_date", newBirthDate);
                monthBox.setEnabled(false);
                dayBox.setEnabled(false);
                yearBox.setEnabled(false);
                Birth_date=yearBox.getSelectedItem().toString()+"-"+month+"-"+dayBox.getSelectedItem().toString();
                newBirthDate="";
                
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_EditBirthActionPerformed

    private void EditGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditGenderActionPerformed
        // TODO add your handling code here:
        try{
        MaleRadio.setEnabled(true);
        FemaleRadio.setEnabled(true);
        if(MaleRadio.isSelected())
            newGender=MaleRadio.getText();
        else
            newGender=FemaleRadio.getText();
        if(!Gender.equals(newGender)){
        if(MaleRadio.isSelected()){
            Teacher.updateTeacherData("person", P_id, "gender", MaleRadio.getText());
            Gender=MaleRadio.getText();
            newGender="";
             MaleRadio.setEnabled(false);
        FemaleRadio.setEnabled(false);
        }else{
            Teacher.updateTeacherData("person", P_id, "gender", FemaleRadio.getText());
            Gender=FemaleRadio.getText();
            newGender="";
            MaleRadio.setEnabled(false);
        FemaleRadio.setEnabled(false);
        }
        }
        }catch(Exception e){ }
    }//GEN-LAST:event_EditGenderActionPerformed

    private void EditMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMobActionPerformed
        // TODO add your handling code here:
        MobField.setEditable(true);
        
        if(Mob_no!=""){
            try {
                Teacher.updateTeacherData("person",P_id,"mob_no",Mob_no);
                Mob_no="";
                MobField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(EditFname.getHeight(), EditFname.getWidth(),Image.SCALE_DEFAULT ));        
            EditMob.setIcon(imageIcon);
        }
    }//GEN-LAST:event_EditMobActionPerformed

    private void BackToTeachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToTeachers1ActionPerformed
        // TODO add your handling code here:
        new TeachersGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToTeachers1ActionPerformed
    
    void setValues()throws Exception{
        
        
        Map<String,String> TeachData=Teacher.getTeacherData(P_id);
        /*
        for(String key:TeachData.keySet()){
                 System.out.println(key+" "+TeachData.get(key));
             }
        */
        
        FnameField.setText(TeachData.get("fname"));
          LnameField.setText(TeachData.get("lname"));
        //For setting gender
        Gender=TeachData.get("gender");
        System.out.println(Gender);
        if(Gender.equals(MaleRadio.getText()))
            MaleRadio.setSelected(true);
        else
            FemaleRadio.setSelected(true);
        //Setting birthdate
        Birth_date=TeachData.get("birth_date");
        date=Birth_date.split("-");
        monthBox.setSelectedIndex(Integer.parseInt(date[1]));
        dayBox.setSelectedIndex(Integer.parseInt(date[2])-1);
        yearBox.setSelectedItem(date[0]);
        MobField.setText(TeachData.get("mob_no"));
        emailField.setText(TeachData.get("email"));
        QualField.setText(TeachData.get("qualification"));
        //setting class
        class_id=TeachData.get("class_id");
        ClassBox.addItem(class_id);
        ClassBox.setSelectedItem(class_id);
        //setting image
            ImagePath=TeachData.get("image").replace((char)44,'\\');
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(ImagePath).getImage().getScaledInstance(imageLabel.getHeight(), imageLabel.getWidth(),Image.SCALE_DEFAULT ));        
            imageLabel.setIcon(imageIcon);
        //Setting Subjects
      
            JoinLabel.setText(TeachData.get("join_date"));
            if(TeachData.get("leave_date")!=null){
                LeaveSchoolBtn.setEnabled(false);
            LeaveLabel.setText(TeachData.get("leave_date"));
            
            }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowTeacher("T00170RD").setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ShowTeacher.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToTeachers1;
    private javax.swing.JComboBox<String> ClassBox;
    private javax.swing.JButton EditBirth;
    private javax.swing.JButton EditClass;
    private javax.swing.JButton EditFname;
    private javax.swing.JButton EditGender;
    private javax.swing.JButton EditImageBtn;
    private javax.swing.JButton EditLname;
    private javax.swing.JButton EditMail;
    private javax.swing.JButton EditMob;
    private javax.swing.JButton EditQual;
    private javax.swing.JButton EditSubject;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JTextField FnameField;
    private javax.swing.JLabel JoinLabel;
    private javax.swing.JLabel LeaveLabel;
    private javax.swing.JButton LeaveSchoolBtn;
    private javax.swing.JTextField LnameField;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField MobField;
    private javax.swing.JTextField QualField;
    private javax.swing.JList<String> SubjectList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dayBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
