/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mannagement;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ragha
 */
public class SubjectGUI extends javax.swing.JFrame {

    /**
     * Creates new form SubjectGUI
     */
    private String Sub_name;
    private Subject sub=new Subject();
    private String selectCellValue="";
    //private Object[][] TabData=sub.showSubjects();
    //private String ColName[]= new String[] {"Subect Id","Subject Name"};
    public SubjectGUI()throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SubName = new javax.swing.JTextField();
        ValidSub = new javax.swing.JLabel();
        AddSubBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubTable = new javax.swing.JTable();
        DelSubBtn = new javax.swing.JButton();
        BackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subjects");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setLabelFor(SubName);
        jLabel2.setText("Subject Name");

        SubName.setNextFocusableComponent(AddSubBtn);
        SubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubNameActionPerformed(evt);
            }
        });
        SubName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SubNameKeyReleased(evt);
            }
        });

        AddSubBtn.setText("Add Subject");
        AddSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubBtnActionPerformed(evt);
            }
        });

        try{
            SubTable.setModel(new javax.swing.table.DefaultTableModel(
                sub.showSubjects(),
                new String [] {
                    "Id", "Name"
                }
            ));
            SubTable.setCellSelectionEnabled(true);
            SubTable.setFillsViewportHeight(true);
            SubTable.setRowHeight(30);
            SubTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            SubTable.setShowGrid(false);
        }catch(Exception e){ }
        SubTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SubTable);

        DelSubBtn.setText("Delete Subject");
        DelSubBtn.setEnabled(false);
        DelSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelSubBtnActionPerformed(evt);
            }
        });

        BackToMenu.setText("Back To Menu");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DelSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(SubName, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ValidSub, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(AddSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BackToMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(SubName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ValidSub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DelSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubNameActionPerformed

    private void AddSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubBtnActionPerformed
        try {
            // TODO add your handling code here:
            if(Sub_name!=""){
            
            
            String Sub_id=sub.getSubId(Sub_name);
            System.out.println(Sub_id+" is a subject id");
            sub.Subject(Sub_id, Sub_name);  //To set Values if subID and SubName
            sub.insertSubject();
            Sub_name="";
            SubName.setText(Sub_name);
            createTable();
            }
        } catch (Exception ex) {
            Logger.getLogger(SubjectGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddSubBtnActionPerformed

    private void SubNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubNameKeyReleased
        // TODO add your handling code here:
        Validations valid=new Validations();
        if(valid.Name(SubName.getText())){
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\valid.png").getImage().getScaledInstance(ValidSub.getHeight(), ValidSub.getWidth(), Image.SCALE_DEFAULT));
            ValidSub.setIcon(imageIcon);
            Sub_name=SubName.getText();
        }else{
            ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\ragha\\Documents\\NetBeansProjects\\School_Mannagement\\src\\school_mannagement\\Icons\\invalid.jpg").getImage().getScaledInstance(ValidSub.getHeight(), ValidSub.getWidth(), Image.SCALE_DEFAULT));
            ValidSub.setIcon(imageIcon);
            Sub_name="";
        }
    }//GEN-LAST:event_SubNameKeyReleased

    private void DelSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelSubBtnActionPerformed
        try {
            // TODO add your handling code here:
            
            System.out.println(selectCellValue);
            sub.deleteSub(selectCellValue);
            createTable();
            DelSubBtn.setEnabled(false);
            
        } catch (Exception ex) {
            Logger.getLogger(SubjectGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DelSubBtnActionPerformed

    private void SubTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubTableMouseClicked
        // TODO add your handling code here:
        if(SubTable.getSelectedRow()>-1){
        selectCellValue= (String)SubTable.getValueAt(SubTable.getSelectedRow(), SubTable.getSelectedColumn());  //this statement get data when use selects cell on table and click on Del Subj btn
            DelSubBtn.setEnabled(true);
    }else
            DelSubBtn.setEnabled(false);
    }//GEN-LAST:event_SubTableMouseClicked

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        // TODO add your handling code here:
        new AdminMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
 public void createTable()throws Exception{
SubTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

SubTable.setModel(new javax.swing.table.DefaultTableModel(
    sub.showSubjects(),
    new String [] {
        "Id", "Name"
    }
));

jScrollPane1.setViewportView(SubTable);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SubjectGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SubjectGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSubBtn;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JButton DelSubBtn;
    private javax.swing.JTextField SubName;
    private javax.swing.JTable SubTable;
    private javax.swing.JLabel ValidSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
